### PR TITLE
Scaffolding: Add node_modules to .Rbuildignore, creating it if necessary

### LINKED ISSUE #9: scaffoldReactWidget() should add node_modules/ to .Rbuildignore

### PR DESCRIPTION
**Pull request by alandipert**
Fixes #9

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@alandipert thanks so much.  I am fine with adding a `usethis` dependency, since as you say we already use it in the tutorial, and it provides significant other package building functionality that I think we will likely want to incorporate in the future

I would think we would want to `usethis::use_git_ignore` as well.  Is assuming that a user has `git` ok?  Even if there is a file `.gitignore` without `git` available, I don't think there is any harm done.

**Comment by pvictor** [comment]
+1 to add `usethis::use_git_ignore("node_modules/")`  and `usethis::use_build_ignore("srcjs")`

An other argument to use `usethis` is to can call in `scaffoldReactWidget` : 

```
usethis::use_package("htmltools")
usethis::use_package("htmlwidgets")
usethis::use_package("reactR")
```

to add these packages in DESCRIPTION as dependencies.
Otherwise `scaffoldReactWidget` works perfectly :)

**Comment by alandipert** [comment]
@timelyportfolio OK cool, I brought in `usethis` for the build ignores, and also made the other improvements suggested by @pvictor

**Comment by alandipert** [comment]
@timelyportfolio does this look OK to you now? Thanks in advance for checking it out 😃

**Comment by timelyportfolio** [comment]
@alandipert yes and thanks.  I will test this weekend with a new widget from scratch and likely record if successful to demonstrate the steps for new users.

**Pull request merged**
