### PR TITLE
Add missing input binding method getType

### PR DESCRIPTION
**Pull request by alandipert**
The reactR-generated Shiny input binding was missing an implementation for `getType`, which is required in order for `shiny::registerInputHandler` to work.

This PR adds an implementation that simply identifies the input by the unique name we're already collecting from the user.

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@alandipert makes sense.  I will likely wait a couple of weeks to avoid upsetting our friends at CRAN.

**Comment by timelyportfolio** [comment]
@alandipert just got to play with this and my `rfabric` examples.  I am seeing 

```
Listening on http://127.0.0.1:6004
Warning: Error in <Anonymous>: No handler registered for type checkbox:rfabric.faCheckbox
  [No stack trace available]
Error in (function (name, val, shinysession)  : 
  No handler registered for type checkbox:rfabric.faCheckbox
```

Will package authors need to change their code to work with this change?  Or will the scaffold need to be changed?

I haven't figured out yet what is happening.  Thanks.

**Comment by alandipert** [comment]
Hm, I didn't expect them to. I probably misunderstood what `getType()` is responsible for exactly 🤦‍♂ . I'll be able to look into this next week, and look forward to hearing whatever you discover.

**Comment by timelyportfolio** [comment]
@alandipert I mistakenly thought that `getType()` did not force require `registerInputHandler()`, but [Shiny lines](https://github.com/cran/shiny/blob/3e39f45106f49a855fa984cb669e41e2eac52106/inst/www/shared/shiny.js#L4256-L4260) seem to suggest that it does.  Also, the only `registerInputHandler` for `Shiny` inputs also have a `getType()`.  All the others use default `getType` which returns `false`.

As of now, I think we should revert this commit, but it does seem we need to find a way for a user to provide a `getType()` if necessary.

**Comment by timelyportfolio** [comment]
@alandipert these [Shiny lines](https://github.com/rstudio/shiny/blob/c332c051f33fe325f6c2e75426daaabb6366d50a/R/server-input-handlers.R#L79-L89) confirm that a handler is required if `getType` returns a `:` separated string.

**Pull request merged**
